version: "3"

services:
  rust:
    build:
      context: .
    depends_on:
      - mongodb
      - liquibase
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - ENV=dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=localhost
      - MONGO_INITDB_DATABASE=rust_mongodb
      - MONGODB_NOTE_COLLECTION=notes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_URL=postgres
  liquibase:
    depends_on:
      - postgres
    image: liquibase/liquibase:latest
    command: ["liquibase", "update", "--changeLogFile=changelog/changelog.yaml"]
    ports:
      - 8082:80
    environment: 
      - LIQUIBASE_LOG_LEVEL=fine
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgres:5432/postgres?autoReconnect=true&useSSL=false
      - LIQUIBASE_COMMAND_USERNAME=postgres
      - LIQUIBASE_COMMAND_PASSWORD=postgres
    volumes:
      - ./liquibase:/liquibase/changelog    
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongoexpress:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8083:80
    environment: 
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=postgres
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_PORT=80

