#!/bin/bash
export ME_CONFIG_MONGODB_ADMINUSERNAME=username
export ME_CONFIG_MONGODB_ADMINPASSWORD=password
export ME_CONFIG_MONGODB_SERVER=localhost
export MONGO_INITDB_DATABASE=rust_mongodb
export MONGODB_NOTE_COLLECTION=notes
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export POSTGRES_DB=postgres
export POSTGRES_URL=localhost